### ISSUE TITLE
Use of latest auto_route (0.4.3) instead of 0.2.2

### ISSUE THREAD

**Issue by andrew-a-hall** [bizz84/starter_architecture_flutter_firebase#20] opened 2020-04-19 09:57 UTC
Hi, I'm trying to upgrade this code to use the latest version of auto_route instead of the old one supplied. Auto_route has replaced the native navigator with ExtendedNavigator which you supply through MaterialApp's builder. I've tried a couple of different approaches and I can't see why when the user snaphot gets passed to AuthWidget, the firebase auth now gets stuck on connectionState=waiting and doesn't resolve.

I've tried this:

child: AuthWidgetBuilder(
        databaseBuilder: databaseBuilder,
        builder: (BuildContext context, AsyncSnapshot<User> userSnapshot) {
          return MaterialApp(
            theme: ThemeData(primarySwatch: Colors.indigo),
            builder: ExtendedNavigator<Router>(
              router: Router(),
              initialRoute: Routes.authWidget, 
              initialRouteArgs: AuthWidgetArguments(userSnapshot: userSnapshot)),
          );

..and also:

child: AuthWidgetBuilder(
        databaseBuilder: databaseBuilder,
        builder: (BuildContext context, AsyncSnapshot<User> userSnapshot) {
          return MaterialApp(
            builder: (BuildContext context, nativeNavigator) {
              return Theme(
                data: ThemeData(primarySwatch: Colors.indigo),
                child: ExtendedNavigator<Router>(
                  router: Router(),
                  initialRoute: Routes.authWidget, 
                  initialRouteArgs: AuthWidgetArguments(userSnapshot: userSnapshot), 
                ),
              );
            }
          );
Neither work. Any suggestions. As far I as can tell it should work.
Many thanks,

**Comment by bizz84** [comment] 2020-04-19 17:07
I stopped using auto_route because of this, and other issues.
The problem is that the initialRoute is only built once, even though different userSnapshot values are emitted over time.

Not necessarily an issue with auto_route itself. It’s just the way I need it to work in this project is not suitable.

**Comment by bizz84** [comment] 2020-04-19 20:17
Also answered in more detail here:
https://github.com/bizz84/starter_architecture_flutter_firebase/issues/19
I'll close this issue for now.

**Closed by bizz84** 2020-04-19 20:17 UTC

**Comment by andrew-a-hall** [comment] 2020-04-19 21:46
Thank you, Andrea

Andrew Hall
GM Pharmacy Technology
________________________________
