### ISSUE TITLE
Firestore Pagination

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [bizz84/starter_architecture_flutter_firebase#53] opened 2020-11-10 14:15 UTC
Hi @bizz84 
Thank you for your work, i use your project as starter.
As an enhencement, it would be awesome to enable firestore pagination.

I don't know how to do it properly, specially when combining streams..

**Comment by bizz84** [comment] 2020-11-10 14:50
@Abacaxi-Nelson I'm going to close this as a duplicate of #52. I agree it would be good to add this, though I don't have an ETA for this atm.

**Closed by bizz84** 2020-11-10 14:50 UTC
